[build-system]
requires = ["protobuf ~= 4.21.12", "Faker ~= 20.0.3",
            "setuptools ~= 65.5.0",
            "mysql-connector-python ~= 8.2.0", "python-dateutil ~= 2.8.2",
            "six ~= 1.16.0"]
